[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Markdown"
version = "0.1.0"
description = "create structured markdown content"
dependencies = [
    # Deine Abhängigkeiten
]
